In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
%matplotlib inline

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [4]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
df.fillna("Unavailable", inplace=True)

In [6]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [7]:
import nltk
import re
from nltk.corpus import stopwords

In [8]:
X = df.drop(columns=["label"])
y = df["label"]

In [9]:
X.shape, y.shape

((20800, 4), (20800,))

In [10]:
messages = X.copy()

In [11]:
messages["title"][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [12]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\turjo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()
corpus = []
for i in range(len(messages)):
    review = re.sub("[^a-zA-Z]"," ",messages["title"][i])
    review = review.lower().split()
    review = [lem.lemmatize(word) for word in review if not word in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)

In [14]:
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'life life luxury elton john favorite shark picture stare long transcontinental flight',
 'beno hamon win french socialist party presidential nomination new york time',
 'excerpt draft script donald trump q ampa black church pastor new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll soc

In [15]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [16]:
voc_size = 5000

In [17]:
one_hot_rep = [one_hot(words,voc_size) for words in corpus]

In [18]:
one_hot_rep[1]

[787, 4297, 1247, 3859, 1911, 2635, 3335]

In [19]:
sent_length = 20
embedding_doc = pad_sequences(one_hot_rep,padding="post",maxlen=sent_length)
print(embedding_doc)

[[2701  243 4020 ...    0    0    0]
 [ 787 4297 1247 ...    0    0    0]
 [ 143  423 2359 ...    0    0    0]
 ...
 [ 922 4984 2705 ...    0    0    0]
 [2110 3638 1966 ...    0    0    0]
 [2484 3648 1289 ...    0    0    0]]


In [20]:
embedding_doc[1]

array([ 787, 4297, 1247, 3859, 1911, 2635, 3335,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [21]:
embedding_vector = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector, input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
X_final=np.array(embedding_doc)
y_final=np.array(y)

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=0)

In [24]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
218/218 [==============================] - 8s 12ms/step - loss: 0.3116 - accuracy: 0.8498 - val_loss: 0.1935 - val_accuracy: 0.9206
Epoch 2/10
218/218 [==============================] - 2s 10ms/step - loss: 0.1559 - accuracy: 0.9402 - val_loss: 0.2102 - val_accuracy: 0.9234
Epoch 3/10
218/218 [==============================] - 2s 10ms/step - loss: 0.1110 - accuracy: 0.9605 - val_loss: 0.1956 - val_accuracy: 0.9248
Epoch 4/10
218/218 [==============================] - 2s 10ms/step - loss: 0.0858 - accuracy: 0.9703 - val_loss: 0.2169 - val_accuracy: 0.9267
Epoch 5/10
218/218 [==============================] - 2s 10ms/step - loss: 0.0675 - accuracy: 0.9770 - val_loss: 0.3042 - val_accuracy: 0.9193
Epoch 6/10
218/218 [==============================] - 2s 11ms/step - loss: 0.0522 - accuracy: 0.9831 - val_loss: 0.3144 - val_accuracy: 0.9200
Epoch 7/10
218/218 [==============================] - 2s 10ms/step - loss: 0.0396 - accuracy: 0.9872 - val_loss: 0.3909 - val_accuracy: 0.9103

In [25]:
y_pred = model.predict(X_test)

215/215 [==============================] - 1s 5ms/step


In [26]:
y_pred=np.where(y_pred > 0.6, 1,0)

In [27]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
confusion_matrix(y_test, y_pred)

array([[3118,  272],
       [ 384, 3090]], dtype=int64)

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.92      0.90      3390
           1       0.92      0.89      0.90      3474

    accuracy                           0.90      6864
   macro avg       0.90      0.90      0.90      6864
weighted avg       0.90      0.90      0.90      6864



In [30]:
test_df = pd.read_csv("test.csv")

In [31]:
test_df

id                                              title  \
0     20800  Specter of Trump Loosens Tongues, if Not Purse...   
1     20801  Russian warships ready to strike terrorists ne...   
2     20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3     20803  Tim Tebow Will Attempt Another Comeback, This ...   
4     20804                    Keiser Report: Meme Wars (E995)   
...     ...                                                ...   
5195  25995  The Bangladeshi Traffic Jam That Never Ends - ...   
5196  25996  John Kasich Signs One Abortion Bill in Ohio bu...   
5197  25997  California Today: What, Exactly, Is in Your Su...   
5198  25998  300 US Marines To Be Deployed To Russian Borde...   
5199  25999  Awkward Sex, Onscreen and Off - The New York T...   

                       author  \
0            David Streitfeld   
1                         NaN   
2               Common Dreams   
3               Daniel Victor   
4     Truth Broadcast Network   
...                       ...   
5195               Jody Rosen   
5196      Sheryl Gay Stolberg   
5197             Mike McPhate   
5198                      NaN   
5199              Teddy Wayne   

                                                   text  
0     PALO ALTO, Calif.  —   After years of scorning...  
1     Russian warships ready to strike terrorists ne...  
2     Videos #NoDAPL: Native American Leaders Vow to...  
3     If at first you don’t succeed, try a different...  
4     42 mins ago 1 Views 0 Comments 0 Likes 'For th...  
...                                                 ...  
5195  Of all the dysfunctions that plague the world’...  
5196  WASHINGTON  —   Gov. John Kasich of Ohio on Tu...  
5197  Good morning. (Want to get California Today by...  
5198  « Previous - Next » 300 US Marines To Be Deplo...  
5199  Perhaps you’ve seen the new TV series whose pi...  

[5200 rows x 4 columns]

In [32]:
test_df.isnull().sum()

id          0
title     122
author    503
text        7
dtype: int64

In [33]:
test_df.fillna("Unavailable", inplace=True)

In [34]:
messages = test_df.copy()

In [35]:
messages.shape

(5200, 4)

In [36]:
lem = WordNetLemmatizer()
corpus = []
for i in range(len(messages)):
    review = re.sub("[^a-zA-Z]"," ",messages["title"][i])
    review = review.lower().split()
    review = [lem.lemmatize(word) for word in review if not word in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)

In [37]:
corpus[0]

'specter trump loosens tongue purse string silicon valley new york time'

In [38]:
one_hot_rep = [one_hot(words,voc_size) for words in corpus]

In [39]:
sent_length = 20
embedding_doc = pad_sequences(one_hot_rep,padding="post",maxlen=sent_length)
print(embedding_doc)

[[1890 4119  940 ...    0    0    0]
 [4686 4042 1743 ...    0    0    0]
 [1468 3077  886 ...    0    0    0]
 ...
 [1566 1902 1148 ...    0    0    0]
 [ 529 2087  564 ...    0    0    0]
 [3586  753 2083 ...    0    0    0]]


In [40]:
test_final = np.array(embedding_doc)

In [41]:
predictions = model.predict(test_final)

163/163 [==============================] - 1s 3ms/step


In [42]:
predictions = np.where(predictions>0.6, 1, 0)

In [43]:
pd.DataFrame(predictions,columns=["label"]).to_csv("submit.csv")